# Project information
site_name: "Code With Enoch"
site_description: " code with Enoch George."
site_author: "enochgeorge"
site_url: "https://enochgeorge.com/"

# Copyright
copyright: "&copy; 2021 codewithenoch"

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/enochterrymize/"
edit_uri: ""


# Configuration
docs_dir: "docs_sample"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "green"
    accent: "green"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  logo: 'images/logo.png'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/enochterrymize"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/enochterrymize"
    - icon: "fontawesome/brands/medium"
      link: "https://medium.com/enochterrymize"
  analytics:
    provider: google
    property: G-2XYRNSGJBZ

  

# Page tree
nav:
  - "Home": "index.md"
  - "API Tutorial": "material-for-mkdocs.md"
  - "MarkDown Tutorial": "material-for-mkdocs.md"
  - "API Tutorial": "material-for-mkdocs.md"
  - "JavaScript Projects":
    - "50 Days of Coding":
       - "Day1 ": "javascript-projects/day1.md"
       - "Day2": "javascript-projects/day2.md"
       - "Day3": "javascript-projects/day3.md"
       - "Day4": "javascript-projects/day4.md"
       - "Day5": "javascript-projects/day5.md"
  - "React Native":
      - "Navigation": "hosting-and-deployment/combinations.md"
      - "Netlify": "hosting-and-deployment/netlify.md"
      - "GitHub Pages": "hosting-and-deployment/github-pages.md"
      - "GitLab Pages": "hosting-and-deployment/gitlab-pages.md"
      - "AWS Amplify Console": "hosting-and-deployment/aws-amplify-console.md"
  - "React":
      - "Hooks": "extensions/mathjax.md"
      - "Code Hilite": "extensions/code-hilite.md"
      - "Footnote": "extensions/footnote.md"
  - "GitHub": "license.md"
  - "Linux": "license.md"
  - "Agile / Project Management ": "license.md"
  - "Developer Challenge": "license.md"
